version: '3.1'

services:

  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080

  # server_app:
  #   build: server_app/.
  #   restart: on-failure
  #   depends_on: 
  #     - db
  #   # ports:
  #   #   - 3000:3000
